create table person (
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(150),
	gender VARCHAR(7) NOT NULL,
	data_of_birth DATE NOT NULL,
	country_of_birth VARCHAR(50)
);
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Gregoor', 'Mussettini', 'gmussettini0@google.ru', 'Male', '2022-09-04', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Keelby', 'Batisse', 'kbatisse1@accuweather.com', 'Male', '2022-07-14', 'Russia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Bevvy', 'Ferrarese', 'bferrarese2@psu.edu', 'Female', '2023-02-23', 'Madagascar');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Ibby', 'Espinoza', 'iespinoza3@nymag.com', 'Polygender', '2023-01-04', 'Thailand');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Mela', 'Bradbeer', 'mbradbeer4@hao123.com', 'Female', '2022-08-12', 'Belarus');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Nanni', 'Woodgate', null, 'Female', '2022-11-03', 'Albania');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Burke', 'McCahill', 'bmccahill6@economist.com', 'Male', '2022-03-19', 'France');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Cristen', 'Font', 'cfont7@stanford.edu', 'Female', '2022-04-14', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Bonnee', 'Rosthorn', 'brosthorn8@va.gov', 'Female', '2022-11-19', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Giacomo', 'Scadden', 'gscadden9@github.com', 'Male', '2022-08-22', 'Honduras');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Nestor', 'Wonfor', null, 'Male', '2022-04-18', 'Russia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Gwenni', 'Scone', 'gsconeb@dedecms.com', 'Female', '2022-03-12', 'Philippines');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Theodor', 'Stolli', 'tstollic@umich.edu', 'Male', '2022-06-28', 'Poland');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Emmott', 'Roselli', 'erosellid@hud.gov', 'Male', '2022-05-06', 'Pakistan');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Eldredge', 'Lisett', 'elisette@nih.gov', 'Non-binary', '2023-01-18', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Celeste', 'Arias', 'cariasf@eepurl.com', 'Female', '2022-12-04', 'Sweden');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Alvinia', 'Willgress', null, 'Female', '2022-06-13', 'Saudi Arabia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Loy', 'Imbrey', 'limbreyh@sciencedaily.com', 'Male', '2022-11-29', 'Ukraine');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Darrel', 'Nowaczyk', 'dnowaczyki@google.ru', 'Male', '2023-01-29', 'Japan');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Lucilia', 'Mattaser', null, 'Non-binary', '2022-11-09', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Margarete', 'Lamplough', null, 'Female', '2022-06-14', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Marco', 'Kopke', null, 'Male', '2022-07-05', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Leila', 'Davidofski', 'ldavidofskim@feedburner.com', 'Female', '2023-01-30', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Leroy', 'Glantz', null, 'Genderfluid', '2022-09-24', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Heath', 'Duffree', 'hduffreeo@prweb.com', 'Male', '2023-01-17', 'Germany');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Reube', 'Boughtwood', 'rboughtwoodp@odnoklassniki.ru', 'Genderqueer', '2022-11-18', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Zackariah', 'Pionter', null, 'Male', '2022-12-05', 'Canada');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Natale', 'Biesterfeld', null, 'Male', '2022-09-11', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Lin', 'Earland', null, 'Female', '2022-10-23', 'Peru');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Darsey', 'Saw', 'dsawt@illinois.edu', 'Agender', '2022-05-05', 'Czech Republic');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Toby', 'Flaherty', 'tflahertyu@harvard.edu', 'Female', '2022-04-18', 'Poland');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Lance', 'Kaygill', null, 'Male', '2022-10-08', 'Portugal');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Perkin', 'Davoren', 'pdavorenw@discovery.com', 'Male', '2022-08-08', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Tallie', 'Bernardes', 'tbernardesx@freewebs.com', 'Male', '2022-08-31', 'Brazil');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Rona', 'Vaugham', 'rvaughamy@amazon.co.uk', 'Female', '2022-04-28', 'Poland');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Alverta', 'Peele', 'apeelez@sbwire.com', 'Female', '2022-09-13', 'Czech Republic');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Mart', 'Gregon', 'mgregon10@google.nl', 'Male', '2022-10-10', 'Germany');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Rubin', 'Guilder', 'rguilder11@storify.com', 'Male', '2023-02-14', 'Philippines');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Gale', 'Gutierrez', null, 'Female', '2022-04-23', 'Sweden');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Dorolisa', 'Follan', null, 'Female', '2022-06-27', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Reamonn', 'Gaunter', null, 'Male', '2022-09-01', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Fidel', 'Kohlert', null, 'Agender', '2022-04-03', 'Iran');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Carny', 'Voase', 'cvoase16@cdbaby.com', 'Male', '2022-06-01', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Nedi', 'Tunnock', 'ntunnock17@reference.com', 'Female', '2022-05-27', 'Australia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Leeanne', 'Tappington', null, 'Female', '2022-04-18', 'Malaysia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Francyne', 'Shipsey', null, 'Female', '2022-03-31', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Trstram', 'Dillingston', 'tdillingston1a@answers.com', 'Male', '2022-07-03', 'Peru');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Wainwright', 'Carless', 'wcarless1b@ucoz.com', 'Male', '2022-06-11', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Tawnya', 'Marthen', 'tmarthen1c@shinystat.com', 'Female', '2022-06-04', 'Vietnam');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Shelby', 'Lindsell', 'slindsell1d@wsj.com', 'Female', '2022-07-24', 'Sierra Leone');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Cindi', 'Luberti', 'cluberti1e@issuu.com', 'Female', '2022-12-23', 'Nigeria');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Alley', 'Edmans', 'aedmans1f@imageshack.us', 'Male', '2023-01-23', 'Philippines');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Early', 'Lanfer', 'elanfer1g@ted.com', 'Male', '2022-06-15', 'Brazil');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Rene', 'Carass', 'rcarass1h@gizmodo.com', 'Male', '2022-08-10', 'Brazil');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Wallis', 'Leverentz', 'wleverentz1i@chicagotribune.com', 'Female', '2022-08-21', 'Russia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Hebert', 'Woodcock', null, 'Male', '2022-12-23', 'Greece');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Madlen', 'Volleth', 'mvolleth1k@springer.com', 'Female', '2022-07-25', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Lurline', 'Shotton', null, 'Agender', '2022-04-20', 'Greece');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Baxter', 'Meale', 'bmeale1m@timesonline.co.uk', 'Male', '2022-09-19', 'Tunisia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Adrienne', 'McConway', 'amcconway1n@instagram.com', 'Female', '2022-12-19', 'Nigeria');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Betteann', 'Cattellion', 'bcattellion1o@bizjournals.com', 'Female', '2022-03-08', 'Sweden');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Eadmund', 'Griffith', 'egriffith1p@ycombinator.com', 'Non-binary', '2023-02-10', 'Greece');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Alexis', 'Fenix', 'afenix1q@weebly.com', 'Female', '2022-11-23', 'Brazil');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Ilyssa', 'Emes', 'iemes1r@123-reg.co.uk', 'Female', '2022-06-18', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Allyn', 'Ghiraldi', 'aghiraldi1s@mtv.com', 'Female', '2022-03-11', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Leesa', 'Farquarson', 'lfarquarson1t@storify.com', 'Female', '2022-11-29', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Rog', 'Mayell', 'rmayell1u@ox.ac.uk', 'Male', '2022-09-17', 'Brazil');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Brietta', 'Smouten', 'bsmouten1v@washington.edu', 'Female', '2022-11-22', 'Portugal');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Tait', 'Dumblton', null, 'Male', '2022-08-05', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Hank', 'Wetherald', null, 'Male', '2023-02-28', 'Colombia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Shellysheldon', 'Praundl', 'spraundl1y@bravesites.com', 'Male', '2022-09-22', 'Syria');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Ailis', 'Hogbourne', null, 'Genderqueer', '2022-11-27', 'Portugal');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Kordula', 'Willmett', 'kwillmett20@theglobeandmail.com', 'Female', '2022-12-13', 'Ecuador');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Em', 'MacCallion', 'emaccallion21@comcast.net', 'Male', '2023-02-13', 'France');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Jean', 'Luparti', 'jluparti22@jigsy.com', 'Male', '2023-01-13', 'Russia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Cami', 'Briston', 'cbriston23@imdb.com', 'Female', '2022-06-21', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Gerta', 'Singh', 'gsingh24@barnesandnoble.com', 'Female', '2022-07-12', 'Slovenia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Sergei', 'Mucklestone', 'smucklestone25@nyu.edu', 'Male', '2022-03-29', 'Czech Republic');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Kevin', 'Tuckett', 'ktuckett26@storify.com', 'Male', '2022-09-05', 'Slovenia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Oralle', 'Pennigar', 'opennigar27@pcworld.com', 'Female', '2022-11-23', 'Bangladesh');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Ado', 'Whiteson', 'awhiteson28@myspace.com', 'Male', '2023-01-25', 'France');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Zeb', 'Probert', null, 'Male', '2022-10-31', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Trent', 'Plowright', null, 'Male', '2023-02-21', 'Argentina');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Kent', 'Benns', 'kbenns2b@mac.com', 'Male', '2023-03-03', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Cleavland', 'Summerrell', null, 'Male', '2023-03-02', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Gail', 'Attyeo', null, 'Male', '2022-10-24', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Mureil', 'Scathard', 'mscathard2e@sun.com', 'Female', '2022-04-18', 'Zambia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Vito', 'Murrock', 'vmurrock2f@cbsnews.com', 'Male', '2022-03-13', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Wesley', 'Peto', null, 'Male', '2022-07-11', 'Malaysia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Harp', 'Ziehm', 'hziehm2h@mayoclinic.com', 'Male', '2023-01-17', 'Vietnam');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Ingrid', 'Sawney', 'isawney2i@infoseek.co.jp', 'Female', '2022-10-01', 'Portugal');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Joanna', 'Kastel', 'jkastel2j@comcast.net', 'Female', '2022-08-16', 'Poland');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Lucita', 'Crates', 'lcrates2k@mayoclinic.com', 'Polygender', '2022-11-09', 'Pakistan');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Willie', 'Goose', 'wgoose2l@paypal.com', 'Male', '2023-01-04', 'China');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Giorgi', 'Leopard', 'gleopard2m@eventbrite.com', 'Male', '2023-01-10', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Bevan', 'Volcker', 'bvolcker2n@ucoz.com', 'Male', '2022-05-06', 'Indonesia');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Willi', 'Meindl', null, 'Female', '2022-05-23', 'Philippines');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Melania', 'Jobbings', 'mjobbings2p@apache.org', 'Female', '2022-06-25', 'Poland');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Shandie', 'Cuskery', 'scuskery2q@smh.com.au', 'Non-binary', '2023-01-14', 'Mexico');
insert into person (first_name, last_name, email, gender, data_of_birth, country_of_birth) values ('Shepherd', 'Cocke', 'scocke2r@examiner.com', 'Male', '2022-10-18', 'Canada');